export const enum PathServices {
  URL = "http://localhost:4000",
  EMPRESA = "/empresa",
  FILE = "/cloudinary",
  LOGIN = "/auth/login",
  ACCESSTOKEN = "/auth/verify",
  LOGOUT = "/auth/logout",
  PROFILE = "/auth/profile",
  USUARIOS = "/usuarios",
  TIPO_SOCIO = "/tipo-socio",
  CARGO = "/cargo",
  TIPO_USUARIO = "/tipo-usuario",
  ACTIVIDAD = "/actividad",
  SECTOR = "/sector",
  DNI = "/api-dni?dni=",
  RUC = "/ruc?ruc=",
  SOCIO = "/socios",
}
